import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { ActivityIndicator, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { Avatar } from "@linespace/ui";
import { colors, radius, spacing } from "@linespace/tokens";
import type { DraftVisibility, PoemDraftSettings, UserSearchResult } from "@linespace/api-client";
import { currentUserId, lineSpaceApi } from "@/services/lineSpaceApi";

export function VisibilityAudienceSheet({ visible, settings, onClose, onChange }: { visible: boolean; settings: PoemDraftSettings; onClose: () => void; onChange: (settings: PoemDraftSettings) => void }) {
  const [query, setQuery] = useState("");
  const [mode, setMode] = useState<Exclude<DraftVisibility, "public">>(settings.visibility === "exclude" ? "exclude" : "include");
  const searchQuery = useQuery({ queryKey: ["compose-audience-search", currentUserId, query], queryFn: () => lineSpaceApi.searchUsers(query, currentUserId), enabled: visible });
  const selected = new Set(settings.audienceUserIds);
  const toggle = (user: UserSearchResult) => {
    const next = new Set(selected);
    if (next.has(user.id)) next.delete(user.id); else next.add(user.id);
    onChange({ ...settings, visibility: mode, isPublic: false, audienceUserIds: [...next] });
  };
  const setVisibility = (next: DraftVisibility) => {
    onChange({ ...settings, visibility: next, isPublic: next === "public", audienceUserIds: next === "public" ? [] : settings.audienceUserIds });
    if (next !== "public") setMode(next);
  };
  const people = searchQuery.data?.results.length ? searchQuery.data.results : [...(searchQuery.data?.recent ?? []), ...(searchQuery.data?.friends ?? [])].filter((person, index, all) => all.findIndex((item) => item.id === person.id) === index);
  return <Modal animationType="slide" onRequestClose={onClose} transparent visible={visible}><View style={styles.root}><Pressable onPress={onClose} style={styles.backdrop} /><View style={styles.sheet}><View style={styles.handle} /><View style={styles.titleRow}><View><Text style={styles.eyebrow}>AUDIENCE</Text><Text style={styles.title}>Who can see this?</Text></View><Pressable onPress={onClose}><Text style={styles.done}>Done</Text></Pressable></View><View style={styles.visibilityRow}>{(["public", "include", "exclude"] as DraftVisibility[]).map((item) => <Pressable key={item} onPress={() => setVisibility(item)} style={[styles.visibilityPill, settings.visibility === item && styles.visibilityPillActive]}><Text style={[styles.visibilityText, settings.visibility === item && styles.visibilityTextActive]}>{item === "public" ? "Everyone" : item === "include" ? "Only selected" : "Everyone except"}</Text></Pressable>)}</View>{settings.visibility !== "public" ? <><View style={styles.modeHint}><Text style={styles.modeHintText}>{mode === "include" ? "Select the people who may read this." : "Select the people who should not see this."}</Text><Text style={styles.count}>{selected.size} selected</Text></View><View style={styles.search}><Text style={styles.searchIcon}>⌕</Text><TextInput autoCapitalize="none" onChangeText={setQuery} placeholder="Search username" placeholderTextColor={colors.tabMuted} style={styles.searchInput} value={query} /></View><ScrollView contentContainerStyle={styles.peopleList}>{searchQuery.isLoading ? <ActivityIndicator color={colors.ink} /> : people.map((person) => <Pressable key={person.id} onPress={() => toggle(person)} style={styles.person}><Avatar color={person.avatarColor} imageSource={person.avatarUrl ? { uri: person.avatarUrl } : undefined} label={person.displayName} size={40} /><View style={styles.personCopy}><Text style={styles.personName}>{person.displayName}</Text><Text style={styles.personHandle}>@{person.handle}{person.isFriend ? " · friend" : person.hasRecentChat ? " · recent chat" : ""}</Text></View><View style={[styles.checkbox, selected.has(person.id) && styles.checkboxActive]}>{selected.has(person.id) ? <Text style={styles.check}>✓</Text> : null}</View></Pressable>)}</ScrollView></> : <View style={styles.publicNote}><Text style={styles.publicIcon}>◎</Text><Text style={styles.publicText}>Anyone on LineSpace can open this post or relay.</Text></View>}</View></View></Modal>;
}

const styles = StyleSheet.create({
  root: { flex: 1, justifyContent: "flex-end" }, backdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(0,0,0,0.28)" }, sheet: { maxHeight: "86%", paddingHorizontal: 18, paddingBottom: 25, borderTopLeftRadius: 26, borderTopRightRadius: 26, backgroundColor: colors.surface }, handle: { alignSelf: "center", width: 42, height: 4, marginTop: 9, borderRadius: radius.pill, backgroundColor: colors.faint }, titleRow: { marginTop: 18, flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between" }, eyebrow: { color: colors.profileMuted, fontSize: 10, letterSpacing: 1.4 }, title: { marginTop: 5, color: colors.ink, fontSize: 24, lineHeight: 30, fontWeight: "600" }, done: { color: colors.ink, fontSize: 14, lineHeight: 20, fontWeight: "600" }, visibilityRow: { marginTop: 18, flexDirection: "row", gap: 7 }, visibilityPill: { flex: 1, minHeight: 42, paddingHorizontal: 7, borderRadius: radius.md, borderWidth: 1, borderColor: colors.line, alignItems: "center", justifyContent: "center", backgroundColor: colors.white }, visibilityPillActive: { borderColor: colors.ink, backgroundColor: colors.ink }, visibilityText: { color: colors.profileMuted, fontSize: 11, textAlign: "center" }, visibilityTextActive: { color: colors.white }, modeHint: { marginTop: 16, flexDirection: "row", justifyContent: "space-between" }, modeHintText: { flex: 1, color: colors.profileMuted, fontSize: 12, lineHeight: 17 }, count: { marginLeft: 8, color: colors.ink, fontSize: 12, lineHeight: 17, fontWeight: "600" }, search: { height: 44, marginTop: 12, paddingHorizontal: 11, borderRadius: 14, backgroundColor: colors.white, flexDirection: "row", alignItems: "center" }, searchIcon: { color: colors.profileMuted, fontSize: 20 }, searchInput: { flex: 1, marginLeft: 7, color: colors.ink, fontSize: 14 }, peopleList: { paddingVertical: 10 }, person: { minHeight: 60, paddingVertical: 8, flexDirection: "row", alignItems: "center" }, personCopy: { flex: 1, marginLeft: 11 }, personName: { color: colors.ink, fontSize: 14, lineHeight: 19, fontWeight: "600" }, personHandle: { marginTop: 2, color: colors.profileMuted, fontSize: 11, lineHeight: 15 }, checkbox: { width: 24, height: 24, borderRadius: 12, borderWidth: 1, borderColor: colors.faint, alignItems: "center", justifyContent: "center" }, checkboxActive: { backgroundColor: colors.ink, borderColor: colors.ink }, check: { color: colors.white, fontSize: 15 }, publicNote: { minHeight: 118, marginTop: 18, padding: 18, borderRadius: radius.md, backgroundColor: colors.surfaceWarm, flexDirection: "row", alignItems: "center" }, publicIcon: { color: colors.ink, fontSize: 28 }, publicText: { flex: 1, marginLeft: 12, color: colors.profileMuted, fontSize: 13, lineHeight: 18 }
});
