-- Profile progression: an append-only experience ledger drives the public
-- creator/reviewer totals, level, and the two earned profile badges.

create table if not exists public.user_experience (
  user_id text primary key references public.users(id) on delete cascade,
  creator_experience integer not null default 0 check (creator_experience >= 0),
  reviewer_experience integer not null default 0 check (reviewer_experience >= 0),
  total_experience integer not null default 0 check (total_experience >= 0),
  level integer not null default 0 check (level between 0 and 10),
  updated_at timestamptz not null default now()
);

create table if not exists public.experience_events (
  id bigint generated by default as identity primary key,
  user_id text not null references public.users(id) on delete cascade,
  category varchar(16) not null check (category in ('creator', 'reviewer')),
  reason varchar(48) not null check (
    reason in (
      'publish_post',
      'publish_thread',
      'participate_thread',
      'content_like',
      'content_save',
      'comment_post',
      'comment_like',
      'comment_save'
    )
  ),
  points integer not null check (points in (2, 5)),
  event_key text not null unique,
  actor_user_id text references public.users(id) on delete set null,
  subject_user_id text references public.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists experience_events_user_created_idx
  on public.experience_events (user_id, created_at desc);
create index if not exists experience_events_category_idx
  on public.experience_events (user_id, category, created_at desc);

insert into public.user_experience (user_id)
select id from public.users
on conflict (user_id) do nothing;

update public.users
set level = least(10, greatest(0, level));

insert into public.badges (id, label, symbol, tone)
values
  ('badge-ink-weaver', 'Ink Weaver · 织墨者', '✒', 'warm'),
  ('badge-soul-echo', 'Soul Echo · 共鸣者', '♧', 'neutral')
on conflict (id) do update
set label = excluded.label,
    symbol = excluded.symbol,
    tone = excluded.tone;

create or replace function public.recalculate_user_experience()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  creator_total integer;
  reviewer_total integer;
  combined_total integer;
begin
  select
    coalesce(sum(points) filter (where category = 'creator'), 0),
    coalesce(sum(points) filter (where category = 'reviewer'), 0)
  into creator_total, reviewer_total
  from public.experience_events
  where user_id = new.user_id;

  combined_total := creator_total + reviewer_total;

  insert into public.user_experience (
    user_id,
    creator_experience,
    reviewer_experience,
    total_experience,
    level,
    updated_at
  )
  values (
    new.user_id,
    creator_total,
    reviewer_total,
    combined_total,
    least(10, floor(combined_total / 10.0)::integer),
    now()
  )
  on conflict (user_id) do update set
    creator_experience = excluded.creator_experience,
    reviewer_experience = excluded.reviewer_experience,
    total_experience = excluded.total_experience,
    level = excluded.level,
    updated_at = now();

  update public.users
  set level = least(10, floor(combined_total / 10.0)::integer),
      updated_at = now()
  where id = new.user_id;

  if creator_total >= 20 then
    insert into public.user_badges (user_id, badge_id, display_order)
    values (new.user_id, 'badge-ink-weaver', 10)
    on conflict (user_id, badge_id) do nothing;
  end if;

  if reviewer_total >= 20 then
    insert into public.user_badges (user_id, badge_id, display_order)
    values (new.user_id, 'badge-soul-echo', 20)
    on conflict (user_id, badge_id) do nothing;
  end if;

  return new;
end;
$$;

drop trigger if exists experience_events_recalculate on public.experience_events;
create trigger experience_events_recalculate
after insert on public.experience_events
for each row execute function public.recalculate_user_experience();

create or replace function public.award_profile_experience(
  p_user_id text,
  p_category text,
  p_reason text,
  p_points integer,
  p_event_key text,
  p_subject_user_id text default null
)
returns public.experience_events
language plpgsql
security definer
set search_path = public
as $$
declare
  actor_id text := public.current_linespace_user_id();
  awarded public.experience_events;
begin
  if actor_id is null then
    raise exception using errcode = '42501', message = 'Authenticated profile required';
  end if;

  if p_user_id is null or p_event_key is null or p_event_key = '' then
    raise exception using errcode = '22023', message = 'Experience recipient and event key are required';
  end if;

  if p_category not in ('creator', 'reviewer')
     or p_reason not in (
       'publish_post',
       'publish_thread',
       'participate_thread',
       'content_like',
       'content_save',
       'comment_post',
       'comment_like',
       'comment_save'
     )
     or p_points not in (2, 5) then
    raise exception using errcode = '22023', message = 'Invalid experience event';
  end if;

  insert into public.experience_events (
    user_id,
    category,
    reason,
    points,
    event_key,
    actor_user_id,
    subject_user_id
  )
  values (
    p_user_id,
    p_category,
    p_reason,
    p_points,
    p_event_key,
    actor_id,
    p_subject_user_id
  )
  on conflict (event_key) do update
    set event_key = excluded.event_key
  returning * into awarded;

  return awarded;
end;
$$;

alter table public.user_experience enable row level security;
drop policy if exists "public profile experience is readable" on public.user_experience;
create policy "public profile experience is readable"
on public.user_experience for select
to anon, authenticated
using (true);

alter table public.experience_events enable row level security;
drop policy if exists "users can read their experience events" on public.experience_events;
create policy "users can read their experience events"
on public.experience_events for select
to authenticated
using (user_id = public.current_linespace_user_id());

revoke all privileges on table public.user_experience from anon, authenticated;
grant select (
  user_id,
  creator_experience,
  reviewer_experience,
  total_experience,
  level,
  updated_at
) on public.user_experience to anon, authenticated;

revoke all privileges on table public.experience_events from anon, authenticated;
grant select (
  id,
  user_id,
  category,
  reason,
  points,
  event_key,
  actor_user_id,
  subject_user_id,
  created_at
) on public.experience_events to authenticated;

revoke execute on function public.award_profile_experience(text, text, text, integer, text, text)
  from public, anon;
grant execute on function public.award_profile_experience(text, text, text, integer, text, text)
  to authenticated;
